package:
  name: nrf-commandline-tools
  version: 10.13.0
source:
  url: https://www.nordicsemi.com/-/media/Software-and-other-downloads/Desktop-software/nRF-command-line-tools/sw/Versions-10-x-x/10-13-0/nRF-Command-Line-Tools_10_13_0_Linux64.zip
  sha256: 64a7ce58facea02cc036da8d8ad61a1b56d6f518c7e76dc2c1f2fc9d507a8233
build:
  string: '0'
  binary_relocation: False
  missing_dso_whitelist:
    - /lib64/libdl.so.2
    - /lib/libdl.so.2
    - /lib64/libpthread.so.0
    - /lib64/libstdc++.so.6
    - /lib/libstdc++.so.6
    - /lib64/libm.so.6
    - /lib/libm.so.6
    - /lib64/libgcc_s.so.1
    - /lib64/libc.so.6
    - /lib/libc.so.6
    - /lib64/librt.so.1
    - /lib64/libncurses.so.5
    - /lib64/ld-linux-x86-64.so.2
    - $RPATH/libQtCore.so.4
    - /lib64/libfreetype.so.6
    - /lib64/libSM.so.6
    - /lib64/libICE.so.6
    - /lib64/libXrender.so.1
    - /lib64/libXrandr.so.2
    - /lib64/libXfixes.so.3
    - /lib64/libXcursor.so.1
    - /lib64/libfontconfig.so.1
    - /lib64/libXext.so.6
    - /lib64/libX11.so.6
    - /lib64/libudev.so.1
test:
  commands:
    - mergehex --version
      #- nrfjprog --version
about:
  home: https://www.nordicsemi.com/Software-and-tools/Development-Tools/nRF-Command-Line-Tools
  summary: The nRF Command Line Tools
  description: |
    The nRF Command Line Tools is used for development, programming and debugging of Nordic Semiconductor's nRF51, nRF52, nRF53 and nRF91 Series devices.

  doc_url: https://infocenter.nordicsemi.com/index.jsp?topic=%2Fug_nrf_cltools%2FUG%2Fcltools%2Fnrf_command_line_tools_lpage.html
